name: re_ucm_core
description: "ReUCM Core"
version: 1.1.0
homepage: "https://reucm.pages.dev"
publish_to: none
repository: https://github.com/BooksFine/re_ucm_core

environment:
  sdk: ^3.6.0-334.2.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
